repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-added-large-files
  - repo: https://github.com/checkmake/checkmake.git
    rev: v0.3.2
    hooks:
      - id: checkmake
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.11
    hooks:
      - id: actionlint
        name: actionlint
        files: ^\.github/workflows/.*\.(yml|yaml)$
        args: ["-shellcheck", "shellcheck -S error"]
      - id: actionlint
        alias: actionlint-oneline
        name: actionlint (one line per one error)
        files: ^\.github/workflows/.*\.(yml|yaml)$
        args: ["-oneline", "-shellcheck", "shellcheck -S error"]
        stages: [manual]
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.21.0
    hooks:
      - id: markdownlint-cli2
  - repo: local
    hooks:
      - id: shellcheck
        name: shellcheck
        entry: shellcheck
        language: system
        types: [shell]
        args: ["-x"]
      - id: shellcheck
        alias: shellcheck-diff-output
        name: shellcheck (diff output)
        entry: shellcheck
        language: system
        types: [shell]
        args: ["-f", "diff", "-x"]
        stages: [manual]
      - id: shellcheck
        alias: shellcheck-json-output
        name: shellcheck (json output)
        entry: shellcheck
        language: system
        types: [shell]
        args: ["-f", "json", "-x"]
        stages: [manual]
      - id: prettier-yaml
        name: prettier-yaml
        entry: prettier
        language: node
        additional_dependencies: ["prettier@3.7.4"]
        files: \.(yml|yaml)$
        args: ["--write"]
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.38.0
    hooks:
      - id: yamllint
      - id: yamllint
        alias: yamllint-parsable
        name: "yamllint (parsable output)"
        args: ["--format", "parsable"]
        stages: [manual]
  - repo: https://github.com/docker-compose-linter/pre-commit-dclint
    rev: v3.1.0
    hooks:
      - id: dclint
        language_version: 22.15.0
        files: ^(?:.*/)?(?:docker-)?compose\.ya?ml$
        args: [--fix]
  - repo: https://github.com/hadolint/hadolint
    rev: v2.14.0
    hooks:
      - id: hadolint
  - repo: https://github.com/golangci/golangci-lint
    rev: v2.10.1
    hooks:
      - id: golangci-lint-config-verify
      - id: golangci-lint-fmt
      - id: golangci-lint-full
        types: [file]
        files: '(\.go$|^go\.(mod|sum)$|^\.golangci\.(yml|yaml|toml|json)$)'
  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: v1.0.0-rc.4
    hooks:
      - id: go-test-repo-mod
